let initialTiles = [
  {
    name: "Basement Landing",
    type: "starting",
    floor: "basement",
    doorConfig: "four-way",
    image: "Basement_Landing.png",
    row: 2,
    col: 2,
  },
  {
    name: "Entrance Hall",
    type: "starting",
    floor: "ground",
    doorConfig: "three-way",
    image: "Entrance_Hall.png",
    row: 3,
    col: 2,
  },
  {
    name: "Hallway",
    type: "starting",
    floor: "ground",
    doorConfig: "four-way",
    image: "Hallway.png",
    row: 2,
    col: 2,
  },
  {
    name: "Ground Floor Staircase",
    type: "starting",
    floor: "ground",
    doorConfig: "single",
    image: "Ground_Floor_Staircase.png",
    row: 1,
    col: 2,
  },
  {
    name: "Upper Landing",
    type: "starting",
    floor: "upper",
    doorConfig: "four-way",
    image: "Upper_Landing.png",
    row: 2,
    col: 2,
  },
];

// {
//     name: "",
//     floors: {basement: true, ground: true, upper: false},
//     doorConfig: "",
//     symbol: "",
//     message: "",
// }

let tiles = [
  {
    name: "Armory",
    floors: { basement: true, ground: true, upper: false },
    doorConfig: "corner",
    image: "Armory.png",
    symbol: "none",
    message:
      "When you discover this tile, reveal cards from the top of the item deckuntil you reveal a weapon. Take it and bury the rest",
  },
  {
    name: "Ballroom",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "four-way",
    image: "Ballroom.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Bloody Room",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "corner",
    image: "Bloody_Room.png",
    symbol: "item",
    message: "none",
  },
  {
    name: "Catacombs",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "four-way",
    image: "Catacombs.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Chapel",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "opposing",
    image: "Chapel.png",
    symbol: "omen",
    message: "When you discover htis tile, gain 1 Sanity",
  },
  {
    name: "Charred Room",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "corner",
    image: "Charred_Room.png",
    symbol: "omen",
    message: "",
  },
  {
    name: "Chasm",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "opposing",
    image: "Chasm.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Collapsed Room",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "corner",
    image: "Collapsed_Room.png",
    symbol: "none",
    message:
      "If you end your tur on this tile, make a speed roll. 5+: Nothing happens. 4-0: Place your explorer on the BasementLanding and take one die of Physical damage",
  },
  {
    name: "Conservatory",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "opposing",
    image: "Conservatory.png",
    symbol: "item",
    message: "none",
  },
  {
    name: "Cramped Passageway",
    floors: { basement: true, ground: true, upper: true },
    doorConfig: "four-way",
    image: "Cramped_Passageway.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Crawlspace",
    floors: { basement: true, ground: false, upper: true },
    doorConfig: "three-way",
    image: "Crawlspace.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Dining Room",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "four-way",
    image: "Dining_Room.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Furnace Room",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "three-way",
    image: "Furnace_Room.png",
    symbol: "event",
    message: "If you end your turn on this tile, take one die of Physical damage",
  },
  {
    name: "Gallery",
    floors: { basement: false, ground: false, upper: true },
    doorConfig: "opposing",
    image: "Gallery.png",
    symbol: "event",
    message: "Leads to Ballroom",
  },
  {
    name: "Game Room",
    floors: { basement: true, ground: false, upper: true },
    doorConfig: "four-way",
    image: "Game_Room.png",
    symbol: "item",
    message: "none",
  },
  {
    name: "Graveyard",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "corner",
    image: "Graveyard.png",
    symbol: "omen",
    message: "Leads to the Underground Cavern",
  },
  {
    name: "Guest Quarters",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "corner",
    image: "Guest_Quarters.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Gymnasium",
    floors: { basement: true, ground: true, upper: false },
    doorConfig: "corner",
    image: "Gymnasium.png",
    symbol: "none",
    message: "When you discover this tile, gain 1 Speed",
  },
  {
    name: "Junk Room",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "three-way",
    image: "Junk_Room.png",
    symbol: "item",
    message: "When you discoverthis tile, place an Obstacle token on it",
  },
  {
    name: "Kitchen",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "opposing",
    image: "Kitchen.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Laboratory",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "corner",
    image: "Laboratory.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Larder",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "corner",
    image: "Larder.png",
    symbol: "none",
    message: "When you discover this tile, gain 1 Might",
  },
  {
    name: "Laundry Chute",
    floors: { basement: false, ground: true, upper: false },
    doorConfig: "single",
    image: "Laundry_Chute.png",
    symbol: "none",
    message:
      "Leads to the BasementLanding. If you end your turn on this tile, place your explorer on the Basement Landing",
  },
  {
    name: "Library",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "three-way",
    image: "Library.png",
    symbol: "omen",
    message: "When you discover this tile, gain 1 Knowledge",
  },
  {
    name: "Mystic Elevator",
    floors: { basement: true, ground: true, upper: true },
    doorConfig: "single",
    image: "Mystic_Elevator.png",
    symbol: "none",
    message:
      "Once per turn when you enter this tile, you may roll two dice. Move the Mystic Elevator to an open doorway on: 4+: Any region. 3: Upper Floor. 2: Ground Floor. 1-0: Basement",
  },
  {
    name: "Nursery",
    floors: { basement: true, ground: true, upper: false },
    doorConfig: "corner",
    image: "Nursery.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Observatory",
    floors: { basement: false, ground: false, upper: true },
    doorConfig: "three-way",
    image: "Observatory.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Operating Theatre",
    floors: { basement: true, ground: false, upper: true },
    doorConfig: "corner",
    image: "Operating_Theatre.png",
    symbol: "item",
    message: "none",
  },
  {
    name: "Organ Room",
    floors: { basement: true, ground: false, upper: true },
    doorConfig: "corner",
    image: "Organ_Room.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Panic Room",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "single",
    image: "Panic_Room.png",
    symbol: "omen",
    message:
      "When you discover this tie, if the Secret Stairs tile has not been placed, find it in the tile stack and place it in the Basement. Then, shuffle the tile stack.",
  },
  {
    name: "Primary Bedroom",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "three-way",
    image: "Primary_Bedroom.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Ritual Room",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "corner",
    image: "Ritual_Room.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Salon",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "corner",
    image: "Salon.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Secret Staircase",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "single",
    image: "Single_Staircase.png",
    symbol: "none",
    message: "Leads to the Hallway",
  },
  {
    name: "Soundproofed Room",
    floors: { basement: true, ground: false, upper: true },
    doorConfig: "three-way",
    image: "Soundproofed_Room.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Specimen Room",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "opposing",
    image: "Specimen_Room.png",
    symbol: "omen",
    message: "none",
  },
  {
    name: "Statuary Corridor",
    floors: { basement: false, ground: false, upper: true },
    doorConfig: "opposing",
    image: "Statuary_Corridor.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Tower",
    floors: { basement: false, ground: false, upper: true },
    doorConfig: "opposing",
    image: "Tower.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Underground Cavern",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "four-way",
    image: "Underground_Cavern.png",
    symbol: "event",
    message: "Leads to the Graveyard",
  },
  {
    name: "Underground Lake",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "corner",
    image: "Underground_lake.png",
    symbol: "event",
    message: "none",
  },
  {
    name: "Vault",
    floors: { basement: true, ground: false, upper: false },
    doorConfig: "single",
    image: "Vault.png",
    symbol: "item",
    message: "none",
  },
  {
    name: "Winter Bedroom",
    floors: { basement: false, ground: true, upper: true },
    doorConfig: "corner",
    image: "Winter_Bedroom.png",
    symbol: "omen",
    message: "none",
  },
];

export { initialTiles, tiles };
